filebeat.prospectors:
        #    - type: log
        #    paths:
        #$    - /var/log/nginx/access.log*

  - type: log 
    paths:
    - /var/log/csv/*.csv

    fields:
      csv-test: true
    fields_under_root: true
output.logstash:
  enabled: true
  hosts: ["logstash:5000"]
