filebeat.prospectors:
  - type: log 
    enabled: true
    paths: 
      - /var/log/dev/*.csv
    tags: ["csv-log, dev-log"]

  - type: log 
    enabled: true
    paths: 
      - /var/log/prod/*.csv
    tags: ["csv-log, prod-log]

output.logstash:
  enabled: true
  hosts: ["logstash:5000"]
